version: "3.8"

services:
  api:
    build: .
    environment:
      - PORT=3000
      - ES_HOST=elasticsearch
      - ELASTIC_URL=http://elasticsearch:9200
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - elastic

volumes:
  elasticsearch:
    driver: local

networks:
  elastic:
    driver: bridge
